name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t udagram-api-feed ./udagram-api-feed
    - name: Build the Docker image
      run: docker build -t udagram-api-user ./udagram-api-user
    - name: Build the Docker image
      run: docker build -t udagram-frontend ./udagram-frontend
    - name: Build the Docker image
      run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - name: tag the Docker image
      run: docker tag udagram-api-feed doanvantuyen1910/udagram-api-feed:v1
    - name: tag the Docker image
      run: docker tag udagram-api-user doanvantuyen1910/udagram-api-user:v1
    - name: tag the Docker image
      run: docker tag udagram-frontend doanvantuyen1910/udagram-frontend:v2
    - name: tag the Docker image
      run: docker tag udagram-reverseproxy doanvantuyen1910/reverseproxy:v1
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: push the Docker image
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: push the Docker image
      run: docker push doanvantuyen1910/udagram-api-feed:v1
    - name: push the Docker image
      run: docker push doanvantuyen1910/udagram-api-user:v1
    - name: push the Docker image
      run: docker push doanvantuyen1910/udagram-frontend:v2
    - name: push the Docker image
      run: docker push doanvantuyen1910/reverseproxy:v1
